FROM python:3.9

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install -r requirements.txt 
# pip list --format=freeze > requirements.txt

COPY . .
EXPOSE 8501

RUN [ "python", "./data_collector.py" ]

ENTRYPOINT ["streamlit", "run"]
CMD ["data_explorer.py"]